### ISSUE TITLE
Django 1.9 bug

### ISSUE THREAD

**Issue by orokusaki** [django-pylibmc/django-pylibmc#34]
I decided to give Django 1.9 a try, but I was met with the following exception:

    Traceback (most recent call last):
      File "/app/.heroku/python/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
        response = self.process_exception_by_middleware(e, request)
      File "/app/.heroku/python/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/app/.heroku/python/lib/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
        response = view_func(request, *args, **kwargs)
        return func(*args, **kwargs)
      File "/app/.heroku/python/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 407, in login
        return login(request, **defaults)
      File "/app/.heroku/python/lib/python3.5/site-packages/django/contrib/auth/views.py", line 49, in inner
        return view(request, *args, **kwargs)
      File "/app/.heroku/python/lib/python3.5/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
      File "/app/.heroku/python/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
        response = view_func(request, *args, **kwargs)
        response = view_func(request, *args, **kwargs)
      File "/app/.heroku/python/lib/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
        request.session.cycle_key()
      File "/app/.heroku/python/lib/python3.5/site-packages/django/contrib/sessions/backends/db.py", line 53, in create
    AttributeError: 'super' object has no attribute '_get_memcache_timeout'

**Comment by orokusaki** [comment]
This is fixed in master. I've been so spoiled by pypi lately that I didn't stop to check when the latest release was (the bugfix was 4 days after the last release).
