### ISSUE TITLE
Error: error 26 from memcached_get(:1:CUR_TOPINFO): Transport endpoint is not connected

### ISSUE THREAD

**Issue by imwhatiam** [django-pylibmc/django-pylibmc#48]
When I use django_pylinmc, I got the following error, may I ask what's the reason for these errors and what should I do ?

2017-11-17 14:03:57,376 [ERROR] django.pylibmc:132 get MemcachedError: error 26 from memcached_get(:1:CUR_TOPINFO): Transport endpoint is not connected
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django_pylibmc/memcached.py", line 130, in get
    return super(PyLibMCCache, self).get(key, default, version)
  File "/root/lian-test/seafile-server-6.2.3/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/core/cache/backends/memcached.py", line 84, in get
    val = self._cache.get(key)
Error: error 26 from memcached_get(:1:CUR_TOPINFO): Transport endpoint is not connected
2017-11-17 14:03:57,402 [ERROR] django.pylibmc:132 get MemcachedError: error 26 from memcached_get(:1:CUR_TOPINFO): Transport endpoint is not connected
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django_pylibmc/memcached.py", line 130, in get
    return super(PyLibMCCache, self).get(key, default, version)
  File "/root/lian-test/seafile-server-6.2.3/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/core/cache/backends/memcached.py", line 84, in get
    val = self._cache.get(key)
Error: error 26 from memcached_get(:1:CUR_TOPINFO): Transport endpoint is not connected
2017-11-17 14:03:57,583 [ERROR] django.pylibmc:132 get MemcachedError: error 26 from memcached_get(:1:CUR_TOPINFO): Transport endpoint is not connected
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django_pylibmc/memcached.py", line 130, in get
    return super(PyLibMCCache, self).get(key, default, version)
  File "/root/lian-test/seafile-server-6.2.3/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/core/cache/backends/memcached.py", line 84, in get
    val = self._cache.get(key)
Error: error 26 from memcached_get(:1:CUR_TOPINFO): Transport endpoint is not connected

**Comment by imwhatiam** [comment]
I think I know how to reproduce this problem.

When you start a Django process via gunicorn without `threads` setting, that means `threads=1`, this error msg will surely appear.

This is my django settings related to cache:
```
CACHES = {
    'default': {
        'BACKEND': 'django_pylibmc.memcached.PyLibMCCache',
        'LOCATION': '127.0.0.1:11211',
    }
}
```

**Comment by edmorley** [comment]
Hi!

What version of django-pylibmc, pylibmc and libmemcached are you using? Does this occur on every `cache.get()` call, or just a proportion of them?

**Comment by nijel** [comment]
I'm seeing similar errors on uwsgi startup, but I'm using Django pylibmc backend directly, not by django-pylibmc. It seems to happen just to first request in every thread, though I'm not 100% sure with this. Anyway the error is there really just after (re)starting uwsgi and then it's gone, so it looks like some race condition in initialization.

Having Django==1.11.9 and pylibmc==1.5.2. libmemcached  at 1.0.18 (actually 1.0.18-4.1 Debian package).

**Comment by bal2ag** [comment]
We ran into similar errors. We deployed a fix which was merged into Django upstream by @edmorley () and for a PR is currently open in this library () to stop closing connections on every request (turn `close()` into a no-op for the `Pylibmc` backend). We hit lots of connection errors when we first deployed and had to revert.

After investigation, I realized the errors were only actually happening on our Celery worker instances. The problem is that Celery's default worker class (prefork) spins up new workers using fork, which copies all the memory/open sockets/file descriptors of the parent process into each subprocess. This is done to save memory, but there's a subtle problem: Celery initializes the Django application in the master process before forking. At least in our case, the initialization code calls into Memcache which means it establishes the client connection object before the app is fully initialized, which means each subprocess is sharing the underlying `pylibmc.Client` object.

Because of this, each worker process will attempt to use the same set of sockets as the master process, which I believe is the cause of the connection errors (`libmemcache`, the underlying C library, [is neither thread nor process safe](http://docs.libmemcached.org/libmemcached.html#threads-and-processes)).

We tried to fix this by hooking into Celery's worker_process_init to do the proper actions:
```python
def disconnect_default_cache_on_worker_fork(*args, **kwargs):
    from django.core.cache import cache
    cache._cache.disconnect_all()
```

This seemed to work for a short time, but then we starting seeing the `Transport endpoint is not connected` errors described in this PR when the Celery workers forked and initialized (one of these errors per worker per initialization, it seems), as well as `Timed out waiting for UP message`. These errors seem related to the fact that the `pylibmc.Client` object is not thread safe, yet all the Celery workers are sharing them. These issues seem similar to those discussed here:
https://github.com/lericson/pylibmc/issues/150

So I think it's a problem with Celery using prefork workers. I'm not sure what the right solution is. Probably we will try to run a different Celery worker type (eventlet or greenlet) or make some attempt to use a threadsafe version of `pylibmc.Client` (maybe one of the pools).

Incidentally, we deploy behind `uwsgi` but we use the `lazy-apps` option, which causes app initialization after the fork and thus avoids this issue. Unfortunately I couldn't find a similar option for Celery's prefork workers.

**Comment by bal2ag** [comment]
After investigating, it turns out the issue was that we were touching the cache during app initialization (one of our modules initialized an object that made calls to the cache). This caused it to be initialized with connections open in the main process, and then forked to our Celery and uwsgi worker processes, which would share the connection and cause all kinds of problems.

The solution was to ensure that we didn't touch the cache during app initialization. I was surprised Django allowed this and didn't fail as it does if you try to use ORM models before the app if fully initialized. In any case, make sure you don't hit your cache in your app initialization before you bring this change into your app.
